package com.home_security.web_lead;

import java.io.Serializable;
import javax.persistence.*;
import org.kie.api.definition.type.*;

/**
 * This class was automatically generated by the data modeler tool.
 */

@Entity
@Table(name = "WEBLEADSPLIT")
public class WebLeadSplit implements Serializable {

	private static final long serialVersionUID = -7342269403495664640L;

	@GeneratedValue(generator = "WEBLEADSPLIT_ID_GENERATOR", strategy = GenerationType.AUTO)
	@Id
	@SequenceGenerator(name = "WEBLEADSPLIT_ID_GENERATOR", sequenceName = "WEBLEADSPLIT_ID_SEQ")
	@Column(name = "ID", unique = true)
	private Long id;

	@Label("LOB")
	@Column(name = "LOB")
	private String lob;

	@Label("Name")
	@Column(name = "NAME")
	private String name;

	@Label("Split Ratio")
	@Column(name = "SPLIT_RATIO")
	private Double splitRatio;

	@Label("Live To Date")
	@Column(name = "LIVE_TO_DATE", nullable = true)
	private Double liveToDate;

	@Label("Split Count")
	@Column(name = "SPLIT_COUNT")
	private Integer splitCount;

	@Label("Local Count")
	@Column(name = "LOCAL_COUNT")
	private Integer localCount;

	public WebLeadSplit() {
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getLob() {
		return this.lob;
	}

	public void setLob(String lob) {
		this.lob = lob;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Double getSplitRatio() {
		return this.splitRatio;
	}

	public void setSplitRatio(Double splitRatio) {
		this.splitRatio = splitRatio;
	}

	public Double getLiveToDate() {
		return this.liveToDate;
	}

	public void setLiveToDate(Double liveToDate) {
		this.liveToDate = liveToDate;
	}

	public Integer getSplitCount() {
		return this.splitCount;
	}

	public void setSplitCount(Integer splitCount) {
		this.splitCount = splitCount;
	}

	public Integer getLocalCount() {
		return this.localCount;
	}

	public void setLocalCount(Integer localCount) {
		this.localCount = localCount;
	}

	@Override
	public String toString() {
		return
		"{id: "+id+"\n"+
		" liveToDate: "+liveToDate+"\n"+
		" lob: "+lob+"\n"+
		" localCount: "+localCount+"\n"+
		" name: "+name+"\n"+
		" splitCount: "+splitCount+"\n"+
		" splitRatio: "+splitRatio+"\n"+
		"}\n";
	}

	public WebLeadSplit(Long id, String lob, String name, Double splitRatio, Double liveToDate, Integer splitCount,
			Integer localCount) {
		this.id = id;
		this.lob = lob;
		this.name = name;
		this.splitRatio = splitRatio;
		this.liveToDate = liveToDate;
		this.splitCount = splitCount;
		this.localCount = localCount;
	}

}